// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgiwlcxjvforvylmtqfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnaXdsY3hqdmZvcnZ5bG10cWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTMyMjAsImV4cCI6MjA2MDYyOTIyMH0.FZsv3QhEmKQUsXh5li5obkbnFRtmmOYmbuaWg149LMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);